//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBA.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nace5
    {
        public int Id { get; set; }
        public string nace5 { get; set; }
        public string nace5_tekst { get; set; }
    }
}
