//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bransjefakta
    {
        public decimal orgnr { get; set; }
        public int dunsnr { get; set; }
        public string kommunenr { get; set; }
        public string kommune { get; set; }
        public string fylkesnr { get; set; }
        public string fylke { get; set; }
        public string nace2 { get; set; }
        public string nace2_tekst { get; set; }
        public string nace5 { get; set; }
        public string nace5_tekst { get; set; }
        public int regnskapsår { get; set; }
        public Nullable<long> omsetning { get; set; }
        public Nullable<long> EBITDA { get; set; }
        public Nullable<int> Antall_ansatte { get; set; }
        public Nullable<long> Oms_pr_ansatt { get; set; }
        public Nullable<long> lonnskost_pr_ansatt { get; set; }
        public Nullable<long> driftsmargin { get; set; }
        public string juridisk_navn { get; set; }
    }
}
