//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nace
    {
        public string NaceCode { get; set; }
        public string Source { get; set; }
        public string ClassificationText { get; set; }
        public string EnglishText { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> IsHeadline { get; set; }
        public Nullable<bool> IsPublicSector { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
